Lab1
JoeManyak/NodeJS-Labs pull request #2
Opened 2022-10-20 16:42 UTC by JoeManyak

2022-10-20 16:45 UTC, hxnchar requested changes
а зачем тебе src/index.ts

2022-10-20 16:45 UTC, hxnchar commented on .github/workflow/actions.yml
> +        uses: actions/cache@v2
v3

2022-10-20 16:45 UTC, hxnchar commented on .github/workflow/actions.yml
> +        uses: actions/cache@v2
(cache)

2022-10-20 16:45 UTC, hxnchar commented on .prettierrc.yml
> +arrowParens: always
new line

2022-10-30 09:25 UTC, nosovk commented on .github/workflow/actions.yml
> +        run: npm ci
а что мы кешируем после `npm ci`?
npm ci удаляет node_modules и скачивает все пакеты заново.
Ну и кеш должен вызываться до запуска скачивания модулей

2022-10-30 09:25 UTC, nosovk commented on tsconfig.json
> +    "module": "commonjs",
используем esmodules

2022-10-30 09:26 UTC, nosovk commented on package.json
> +  "main": "index.js",
type забыт

2022-10-30 09:27 UTC, nosovk commented
https://node-js-labs-git-lab1-joemanyak.vercel.app/api/default

2022-10-30 09:27 UTC, nosovk commented
имя defualt поменял бы

2022-10-30 17:39 UTC, JoeManyak commented
новий ендпоїнт https://node-js-labs-r11mtkdio-joemanyak.vercel.app/api/dumpling

2022-10-30 17:41 UTC, nosovk commented on package.json
> +    "*.{ts,css,md}": "prettier --write"
хуки не должны иметь сайд еффектов. Тут мы меняем файлы перед коммитом

2022-10-30 17:42 UTC, nosovk commented on .github/workflow/actions.yml
> +      - name: Install
тут забыт if
кеш выше не будет использоваться, потому что npm ci удалит его и скачает заново.
Чтобы он работал, нужно пропускать npm ci если у нас уже есть закешированный node_modules

2022-11-20 22:13 UTC, nosovk commented
merge

2022-11-21 09:26 UTC, merged